/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d5e3fc",
        "on-error-container": "#93000a",
        "surface-container-low": "#f5f2ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "surface-variant": "#e4e1ee",
        "surface": "#fcf8ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-tint": "#4d44e3",
        "inverse-primary": "#c3c0ff",
        "background": "#fcf8ff",
        "on-surface": "#1b1b24",
        "on-secondary-container": "#57657a",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0ecf9",
        "error-container": "#ffdad6",
        "secondary": "#515f74",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#0d1c2e",
        "secondary-container": "#d5e3fc",
        "tertiary": "#7e3000",
        "inverse-surface": "#302f39",
        "tertiary-container": "#a44100",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "on-primary-container": "#dad7ff",
        "inverse-on-surface": "#f3effc",
        "on-tertiary-container": "#ffd2be",
        "primary-fixed": "#e2dfff",
        "on-background": "#1b1b24",
        "on-primary-fixed-variant": "#3323cc",
        "primary": "#3525cd",
        "surface-container-high": "#eae6f4",
        "surface-dim": "#dcd8e5",
        "tertiary-fixed-dim": "#ffb695",
        "on-tertiary-fixed": "#351000",
        "error": "#ba1a1a",
        "on-surface-variant": "#464555",
        "surface-container-highest": "#e4e1ee",
        "secondary-fixed-dim": "#b9c7df",
        "outline": "#777587",
        "outline-variant": "#c7c4d8",
        "surface-bright": "#fcf8ff",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "slate": {
          "50": "#f8fafc",
          "100": "#f1f5f9",
          "200": "#e2e8f0",
          "300": "#cbd5e1",
          "400": "#94a3b8",
          "500": "#64748b",
          "600": "#475569",
          "700": "#334155",
          "800": "#1e293b",
          "900": "#0f172a",
          "950": "#020617",
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "32px",
        "margin": "32px",
        "sm": "8px",
        "gutter": "24px",
        "xs": "4px",
        "2xl": "48px",
        "md": "16px",
        "unit": "4px",
        "3xl": "64px",
        "lg": "24px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "h2": ["Inter"],
        "h3": ["Inter"],
        "label-md": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "h2": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h3": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h1": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      boxShadow: {
        'natural-soft': '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
      },
    },
  },
  plugins: [],
};
